In [1220]:
#创建   dataframe的创建方式
import pandas as pd
import numpy as np
#通过serise来创建
s1 = pd.Series([1,2,3,4,5,])
s2 = pd.Series([6,7,8,9,10])
df = pd.DataFrame({"第一列":s1,"第二列":s2 })
df

   第一列  第二列
0    1    6
1    2    7
2    3    8
3    4    9
4    5   10

In [1221]:
# 通过字典来创建
df = pd.DataFrame(
    {

        "name":["tom","jack","alice","bob","allen"],
        "age":[10,20,30,40,50],
        "score":[100,200,300,400,500]
    },index=[1,2,3,4,5],columns=["name","age","score"]# 可以自定义顺序
)
df

    name  age  score
1    tom   10    100
2   jack   20    200
3  alice   30    300
4    bob   40    400
5  allen   50    500

In [1222]:
# dataframe 的属性
print('行索引:')
print(df.index )
print('列标签:')
print(df.columns)
print('值')
print(df.values)

行索引:
Index([1, 2, 3, 4, 5], dtype='int64')
列标签:
Index(['name', 'age', 'score'], dtype='object')
值
[['tom' 10 100]
 ['jack' 20 200]
 ['alice' 30 300]
 ['bob' 40 400]
 ['allen' 50 500]]

In [1223]:
print('维度',df.ndim)
print('形状',df.shape) # 行   列
print('元素个数',df.size)
print('数据类型',df.dtypes)

维度 2
形状 (5, 3)
元素个数 15
数据类型 name     object
age       int64
score     int64
dtype: object

In [1224]:
# T
#行数转置 交换
print(df.T)
df

         1     2      3    4      5
name   tom  jack  alice  bob  allen
age     10    20     30   40     50
score  100   200    300  400    500

    name  age  score
1    tom   10    100
2   jack   20    200
3  alice   30    300
4    bob   40    400
5  allen   50    500

In [1225]:
# 获取元素 loc  iloc at  iat
# 某行
print(df.loc[4])
print(df.iloc[3])# 从0开始

name     bob
age       40
score    400
Name: 4, dtype: object
name     bob
age       40
score    400
Name: 4, dtype: object

In [1226]:
df

    name  age  score
1    tom   10    100
2   jack   20    200
3  alice   30    300
4    bob   40    400
5  allen   50    500

In [1227]:
print(df.loc[:,'name'])
print(df.iloc[:,0])
print(df.name)

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object

In [1228]:
df

    name  age  score
1    tom   10    100
2   jack   20    200
3  alice   30    300
4    bob   40    400
5  allen   50    500

In [1229]:
#单个数据
print(df.at[3,'score'])
print(df.iat[2,2])
print(df.loc[3,'score'])

300
300
300

In [1230]:
# 获取单列数据
print(df['name'])
print(type(df['name']))
print(df.name)
print(type(df.name))
print(df[['name']])
print(type(df[['name']]))
df[['name']]

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
<class 'pandas.core.series.Series'>
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
<class 'pandas.core.series.Series'>
    name
1    tom
2   jack
3  alice
4    bob
5  allen
<class 'pandas.core.frame.DataFrame'>

    name
1    tom
2   jack
3  alice
4    bob
5  allen

In [1231]:
#获取多列的数据
print(df[['name','age']])
print(df[['name','age','score']])
df[['name','age']]

    name  age
1    tom   10
2   jack   20
3  alice   30
4    bob   40
5  allen   50
    name  age  score
1    tom   10    100
2   jack   20    200
3  alice   30    300
4    bob   40    400
5  allen   50    500

    name  age
1    tom   10
2   jack   20
3  alice   30
4    bob   40
5  allen   50

In [1232]:
#查看部分数据
print(df.head(2))
print(df.tail(2))

   name  age  score
1   tom   10    100
2  jack   20    200
    name  age  score
4    bob   40    400
5  allen   50    500

In [1233]:
# 使用不二索引帅选



df[(df.score>300)&(df.age>20)]

    name  age  score
4    bob   40    400
5  allen   50    500

In [1234]:
# 随机抽样
df.sample(5)

    name  age  score
5  allen   50    500
2   jack   20    200
1    tom   10    100
4    bob   40    400
3  alice   30    300

In [1235]:
df
#查看元素是否在包含的参数集合中
print(df.isin(['jack']))

    name    age  score
1  False  False  False
2   True  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [1236]:
print(df['score'].sum())# 某一列的求和
print(df.score.mean())
print(df.score.max())
print(df.score.min())
print(df.score.std())#标准差
print(df.score.var())
print(df.score.quantile(0.25))

1500
300.0
500
100
158.11388300841898
25000.0
200.0

In [1237]:
print(df.describe() )

             age       score
count   5.000000    5.000000
mean   30.000000  300.000000
std    15.811388  158.113883
min    10.000000  100.000000
25%    20.000000  200.000000
50%    30.000000  300.000000
75%    40.000000  400.000000
max    50.000000  500.000000

In [1238]:
#个数
print(df.count())

name     5
age      5
score    5
dtype: int64

In [1239]:
print(df.value_counts()) # 出现的次数频率

name   age  score
alice  30   300      1
allen  50   500      1
bob    40   400      1
jack   20   200      1
tom    10   100      1
Name: count, dtype: int64

In [1240]:
print(df.drop_duplicates() )#去重

    name  age  score
1    tom   10    100
2   jack   20    200
3  alice   30    300
4    bob   40    400
5  allen   50    500

In [1241]:
# 检查是否重复
print(df.duplicated(subset=['age']))

1    False
2    False
3    False
4    False
5    False
dtype: bool

In [1242]:
print(df.replace(40,50))

    name  age  score
1    tom   10    100
2   jack   20    200
3  alice   30    300
4    bob   50    400
5  allen   50    500

In [1243]:
df

    name  age  score
1    tom   10    100
2   jack   20    200
3  alice   30    300
4    bob   40    400
5  allen   50    500

In [1244]:
df.cumsum()# 累加
df.cummin()

    name  age  score
1    tom   10    100
2   jack   10    100
3  alice   10    100
4  alice   10    100
5  alice   10    100

In [1245]:
#排序
print(df.sort_index(ascending=False) )

    name  age  score
5  allen   50    500
4    bob   40    400
3  alice   30    300
2   jack   20    200
1    tom   10    100

In [1246]:
print(df.sort_values(by=['score','age']))

    name  age  score
1    tom   10    100
2   jack   20    200
3  alice   30    300
4    bob   40    400
5  allen   50    500

In [1247]:
df.nlargest(2,columns=['score','age'])

    name  age  score
5  allen   50    500
4    bob   40    400

In [1248]:
import pandas as pd
data = {
    '姓名':['张三','李四','王五','赵路','小明',],
    '数学':[85,92,78,88,95],
    '英语':[90,88,85,92,80],
    '物理':[75,80,88,85,90]

}

scores = pd.DataFrame(data)
scores

   姓名  数学  英语  物理
0  张三  85  90  75
1  李四  92  88  80
2  王五  78  85  88
3  赵路  88  92  85
4  小明  95  80  90

In [1249]:
# 计算学生的总分和平均分
scores['总分'] = scores[['数学','英语','物理']].sum(axis=1)
scores
scores ['平均分'] = scores ['总分']/3
scores
scores ['平均分2']= scores[['数学','英语','物理']].mean(axis=1)
scores

   姓名  数学  英语  物理   总分        平均分       平均分2
0  张三  85  90  75  250  83.333333  83.333333
1  李四  92  88  80  260  86.666667  86.666667
2  王五  78  85  88  251  83.666667  83.666667
3  赵路  88  92  85  265  88.333333  88.333333
4  小明  95  80  90  265  88.333333  88.333333

In [1250]:
# 找出数学成绩高于90分或者英语成绩高于85分的学生
scores[(scores['数学']>90 )&(scores['英语']>85)]
r1 = scores.sort_values('总分',ascending=False).head(3)

In [1251]:
r2 = scores.nlargest(3,columns=['总分'] )
print(r1)
print(r2)

   姓名  数学  英语  物理   总分        平均分       平均分2
4  小明  95  80  90  265  88.333333  88.333333
3  赵路  88  92  85  265  88.333333  88.333333
1  李四  92  88  80  260  86.666667  86.666667
   姓名  数学  英语  物理   总分        平均分       平均分2
3  赵路  88  92  85  265  88.333333  88.333333
4  小明  95  80  90  265  88.333333  88.333333
1  李四  92  88  80  260  86.666667  86.666667

In [1252]:
import pandas as pd

data = {
    '产品单价':['A','B','C','D',],
    '单价':[100,150,200,120],
    '销量':[50,30,20,40]
}

df = pd.DataFrame(data)
df['总销售额'] = df['单价']*df['销量']
df

  产品单价   单价  销量  总销售额
0    A  100  50  5000
1    B  150  30  4500
2    C  200  20  4000
3    D  120  40  4800

In [1253]:
df.nlargest(1,columns= ['总销售额'])
df.sort_values('总销售额',ascending=False)

  产品单价   单价  销量  总销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000